<template>
    <div class="field inputfields">
        <label><b>Add Citizen</b></label>
        <div class="fields">
            <!-- When a citizen is created, make sure to generate an id for them aswell -->
            <div class="initinput">
                <Label><p>Age</p></Label>
                <input type="number" steps="0.01" v-model="citizen.age">
                <!-- and birthdate?, An autochecked autogenerate, or uncheck to specify possibly? -->
            </div>
            <div class="input">
                <label><p>Name</p></label>
                <input type="text" v-model="citizen.name">
                <!-- Autogenerate autochecked, but can uncheck and manualy name
                Autogenerated name generates a surname based on the father feks "Olavsson" eller "Fredriksson"
                or for english, use a english surname list and select some -->
            </div>
            <div class="input">
                <label><p>Surname</p></label>
                <input type="text" v-model="citizen.surname">
            </div>
            <div class="input">
                <label><p>Home city/ unit assignment</p></label>
                <v-select label="City or Division" :options="data.cityordivision" v-model="citizen.cityordivision"></v-select>
                <!-- Dropdown with city selection or a selection for division thye belong to, like
                military 1, eastern watch, mining guild etc. -->
            </div>
            <div class="input">
                <label><p>Profession</p></label>
                <v-select label="profession" :options="data.professions" v-model="citizen.profession"></v-select>
                <!-- Dropdown with professions -->
            </div>
            <div class="input">
                <label><p>Availability for new tasks (unchecked means not available)</p></label>
                <input class="inputbox" type="checkbox" v-model="citizen.available">
            </div>
        </div>
        <button v-on:click="submit">Submit</button>
    </div>
</template>

<script>
import backMain from "./../../backend/BackMain.js"
import shortid from 'shortid';
import clonedeep from 'lodash.clonedeep'

export default {
    name: "AddCitizen",
    data() {
        return {
            citizen: {
                id : "",
                age : 0,
                name: "",
                surname: "",
                cityordivision: "",
                Profession: "",
                task: "",
                available: false
            },
            data : {}
        }
    },
    mounted: function() {
        this.data = backMain.getData()
    },
    methods: {
        getData: function(){
            this.data = backMain.getData()
        },
        submit: function(){
            let tmp = backMain.getData()
            this.citizen.id = shortid.generate()
            this.citizen.age = parseFloat(this.citizen.age)
            tmp.citizen.push(clonedeep(this.citizen))
            backMain.setData(clonedeep(clonedeep(tmp)))
            this.citizen = {
                id : "",
                age : 0,
                name: "",
                cityordivision: "",
                Profession: "",
                task: "",
                available: false
            }
            this.getData();
        }
    }
}
</script>

<style scoped>
.input {
    padding-left: 5em;
}
.inputfields {
    display: inline-block;
}
</style>
